- Name: fileName
  ProductCode:
  - sds
  - pdi
  - xns
  - sao
  - pds
  - sig
  - pts
  - sfs
  - sfc
  - sss
  Description_EN: The file name
  Sample:
  - spoolss
  - hosts
  - svcrestarttask
  DL_Type: dynamic
  DL_CommonKey:
  - FileName
  DL_Searchable: true
  DL_Aggregable: true
- Name: compressedFileName
  ProductCode:
  - pdi
  - xns
  - sao
  - sfs
  - sfc
  - sds
  - sss
  - scs
  Description_EN: The file name of the compressed file
  Sample:
  - /proc/32058/fd/150
  - NONAMEFL
  - /proc/10006/fd/30
  - VirusActionSample/RPF2_OtherMalwareSample-other.exe
  DL_Type: string
  DL_CommonKey:
  - FileName
  DL_Searchable: true
  DL_Aggregable: false
- Name: filePath
  ProductCode:
  - sds
  - pds
  - sao
  - pdi
  - xns
  - pts
  - sfs
  - sfc
  Description_EN: The file path without the file name
  Sample:
  - security
  - /var/log/audit/audit.log
  - application
  DL_Type: string
  DL_CommonKey:
  - FileFullPath
  DL_Searchable: true
  DL_Aggregable: true
- Name: fileHash
  ProductCode:
  - sds
  - pdi
  - xns
  - pds
  - sao
  - sig
  - sfs
  - sfc
  - sss
  - ddr
  Description_EN: The SHA-1 of the file that triggered the rule or policy
  Sample:
  - DA39A3EE5E6B4B0D3255BFEF95601890AFD80709
  - 89CE26EAD139D52B8A6B61BFFC6AF89AF246580F
  - 3AD1F4E7CAA11E5199EE80B8983677ADDD065450
  DL_Type: string
  DL_CommonKey:
  - FileSHA1
  DL_Searchable: true
  DL_Aggregable: true
- Name: compressedFileHash
  ProductCode:
  - pdi
  - xns
  - sfs
  - sfc
  - sds
  - sao
  - sss
  Description_EN: The SHA-1 of the decompressed archive
  Sample:
  - 6E2ECB34B7798E179CC704111FB9733FBAAD5ACA
  - FA71B59F35F0EE44D27F74917EF5A0DA2797E80B
  - 14D2302172EB81465CE12E01361AE24CDE170F7B
  DL_Type: string
  DL_CommonKey:
  - FileSHA1
  DL_Searchable: true
  DL_Aggregable: false
- Name: fileHashSha256
  ProductCode:
  - pdi
  - xns
  - sao
  - sig
  - sds
  - sfs
  - sfc
  - sss
  - scs
  Description_EN: The SHA-256 of the file (fileName)
  Sample:
  - 6A6EB2D717CEA041B4444193B45EDFB6CA1287518203B7230B3C4B8FFB031EAB
  - BFF703FF836196644586014DA13A097C2EE9A08E4D596DFB7C8E0F685FE01294
  - 12327F460AC9CBBC34D39EB3CF89C7FECCA37F08773A04566840F73F6ECC4104
  DL_Type: string
  DL_CommonKey:
  - FileSHA2
  DL_Searchable: true
  DL_Aggregable: false
- Name: compressedFileHashSha256
  ProductCode:
  - pdi
  - xns
  - sfs
  - sfc
  - sds
  - sao
  - sss
  Description_EN: The SHA-256 of the compressed suspicious file
  Sample:
  - 60C7C5924DD09F7C6B150120FB92DCEE00AE82DB75C7402FA4D9152CF487A94F
  - 482FFC4F87B78C3C7073983CF65B593D9F13F0A3D6DC54B4A3F616F79838F3CE
  - 68C0126D9B4B0FC32DE181D0D67DA8FE82E23745F6023317D5E053B6F6ED26CF
  DL_Type: string
  DL_CommonKey:
  - FileSHA2
  DL_Searchable: true
  DL_Aggregable: false
- Name: objectType
  ProductCode:
  - sca
  - sds
  - sao
  - sem
  - xes
  - sfs
  Description_EN: The object type
  Sample:
  - file
  - process
  - qil
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: malName
  ProductCode:
  - sao
  - sds
  - pdi
  - xns
  - pds
  - sws
  - pts
  - xms
  - sfs
  - sfc
  - sss
  - scs
  Description_EN: The name of the detected malware
  Sample:
  - SecurityLevelDrop
  - Regla Logs All
  - USR_SUSPICIOUS_DOMAIN.UMXX
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: eventName
  ProductCode:
  - sds
  - pdi
  - xns
  - sao
  - pds
  - ptp
  - sca
  - sem
  - xes
  - stp
  - sig
  - ptn
  - szn
  - pts
  - xms
  - sfs
  - sfc
  - sss
  - ams
  - mns
  - ddr
  Description_EN: The event type
  Sample:
  - LOG_INSPECTION_EVENT
  - SECURITY_RISK_DETECTION
  - WEB_THREAT_DETECTION
  - LOG_INSPECTION_EVENT
  - MALWARE_DETECTION
  - PROCESS_ACTIVITY
  - WEB_POLICY_VIOLATION
  - DEEP_PACKET_INSPECTION_EVENT
  - INTEGRITY_MONITORING_EVENT
  - DISRUPTIVE_APPLICATION_DETECTION
  - PRODUCT_SUMMARY
  - PRODUCT_UPDATE
  - BEHAVIORAL_VIOLATION
  - FIREWALL_POLICY_VIOLATION
  - SUSPICIOUS_BEHAVIOUR_DETECTION
  - DENYLIST_CHANGE
  - MACHINE_LEARNING_DETECTION
  - DLP_VIOLATION
  - MALWARE_OUTBREAK_DETECTION
  - SENSITIVE_DATA_DETECTION
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: true
- Name: remarks
  ProductCode:
  - sds
  - pdi
  - xns
  - pds
  - sca
  - sao
  - sem
  - stp
  - ptn
  - xms
  - sfs
  - sss
  - sig
  Description_EN: The additional information
  Sample:
  - 'warning: fork: Resource temporarily unavailable'
  - 'pam_unix(cron:session): session opened for user root by (uid=0)'
  - "WinEvtLog: Application: AUDIT_FAILURE(18470): MSSQL$SA: (no user): no domain:
    EXAMPLE.com: Login failed for user 'example_user'. Reason: The account is disabled.
    [CLIENT: 10.10.10.10]  "
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: fullPath
  ProductCode:
  - sds
  - sao
  - pdi
  - xns
  - pds
  - pts
  - sfs
  - sfc
  - sss
  - scs
  Description_EN: The combination of the file path and the file name
  Sample:
  - \etc\hosts
  - c:\windows\system32\tasks\microsoft\windows\softwareprotectionplatform\svcrestarttask
  - \var\log\auth.log
  DL_Type: string
  DL_CommonKey:
  - FileFullPath
  DL_Searchable: true
  DL_Aggregable: false
- Name: scanType
  ProductCode:
  - sca
  - sem
  - sds
  - sao
  - pds
  - xms
  - sfs
  - sss
  - scs
  Description_EN: The scan type
  Sample:
  - realtime_mailmeta-exchange
  - exchange_mailbox_realtime_detection_logs
  - gateway_realtime_blocking_traffic
  - malware_schedule_image
  - malware_schedule_file
  - malware_realtime_image
  - malware_realtime_file
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: compressedFileSize
  ProductCode:
  - pdi
  - xns
  - sfs
  - sfc
  Description_EN: The file size of the decompressed archive file
  Sample:
  - '0'
  - '265314'
  - '175864'
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: compressedFileType
  ProductCode:
  - pdi
  - xns
  - sfs
  - sfc
  - sss
  Description_EN: The file type of the decompressed archive file
  Sample:
  - EXE
  - JAVA
  - PDF
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: engType
  ProductCode:
  - sao
  - sfs
  Description_EN: The engine type
  Sample:
  - Virus Scan Engine (Windows XP/Server 2003, x64)
  - Virus Scan NT Kernel Engine
  - Spyware/Grayware Scan Engine v.6 (64-bit)
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: engVer
  ProductCode:
  - xes
  - sca
  - sao
  - sfs
  Description_EN: The engine version
  Sample:
  - 1.0.0.1123_1.0.0.1101
  - 9.0.1004
  - 22.540.1001
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: eventId
  ProductCode:
  - sds
  - pdi
  - xns
  - sao
  - pds
  - sca
  - xes
  - sem
  - pts
  - scs
  - xms
  - sfs
  - sfc
  - sss
  - ams
  - mns
  - ddr
  Description_EN: The event ID from the logs of each product
  Sample:
  - 100100
  - 100101
  - 100116
  - 100117
  - 100119
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: true
- Name: fileSize
  ProductCode:
  - pdi
  - xns
  - sig
  - sao
  - sfs
  - sfc
  - sss
  Description_EN: The file size of the suspicious file
  Sample:
  - '0'
  - '1255856'
  - '1237880'
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: fileType
  ProductCode:
  - pdi
  - xns
  - sig
  - sfs
  - sfc
  - sss
  - scs
  Description_EN: The file type of the suspicious file
  Sample:
  - EXE
  - LNK
  - MIME
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: malFamily
  ProductCode:
  - pdi
  - xns
  - sao
  - sds
  - sfs
  Description_EN: The threat family
  Sample:
  - EQUATED
  - STARTER
  - '0'
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: malSubType
  ProductCode:
  - sao
  - sfs
  Description_EN: The subsidiary virus type
  Sample:
  - Unknown
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: malType
  ProductCode:
  - pdi
  - xns
  - sds
  - sao
  - pds
  - sfs
  - scs
  Description_EN: The risk type for Network Content Correlation Engine rules
  Sample:
  - OTHERS
  - MALWARE
  - Others
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: malTypeGroup
  ProductCode:
  - pdi
  - xns
  - sfs
  Description_EN: The risk type group for NCCE (Network Content Correlation 
    Engine) rules. This field comes from NCCP (Network Content Correlation 
    Pattern) rule type definitions.
  Sample:
  - Others
  - Malware
  - Spyware
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: pver
  ProductCode:
  - sds
  - pdi
  - xns
  - pds
  - sao
  - ptp
  - stp
  - sig
  - ams
  - scs
  - sfs
  - sfc
  - sss
  Description_EN: The product version
  Sample:
  - 20.0.0.4726
  - 20.0.0.4416
  - 6.2.1125
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: confidence
  ProductCode:
  - sao
  - sfs
  Description_EN: The confidence rating returned from TrendX Hybrid Model 
    (predictive machine learning). Values from 1-99.
  Sample:
  - 94
  DL_Type: int
  DL_CommonKey:
  DL_Searchable: false
  DL_Aggregable: false
- Name: reportGUID
  ProductCode:
  - sca
  - sfs
  - pdi
  - xns
  Description_EN: The GUID for Workbench to request report page data
  Sample:
  - 00000000-0000-0000-0000-000000000000
  - 11111111-1111-1111-1111-111111111111
  - 22222222-2222-2222-2222-222222222222
  DL_Type: string
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
- Name: customTags
  ProductCode:
  - scs
  - sfs
  Description_EN: The event tags
  Sample:
  - network
  - mitre_discovery
  DL_Type: dynamic
  DL_CommonKey:
  DL_Searchable: true
  DL_Aggregable: false
